---
title: "Challenge 7"
author: "Natalie Simbolon"
date: "12/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Loading Packages, message = FALSE}
library(tidyverse)
library(tidytuesdayR)
library(janitor)
```

```{r Importing Data}
tuesdata <- tidytuesdayR::tt_load(2021, week = 8, auth = "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")

furniture <- tuesdata$furniture %>% 
  clean_names()

furniture
```

```{r}
furniture_spiral = furniture %>% 
  add_row(year = 1990, houshold_value_dollars = 0, .before = 1)%>%
  mutate(year = as.factor(year),
         y = seq(10, by = -1.5, length.out = 7),
         x = 0) %>%
  rowwise() %>%
  mutate(xend = min(houshold_value_dollars, max_x),
         yend = slope*xend + y) %>%
  mutate(y_2 = yend,
         x_2 = 0,
         xend_2 = if_else(houshold_value_dollars < max_x,
                          NA_real_, houshold_value_dollars - max_x),
         yend_2 = slope*xend_2 + y_2) 

```

```{r Figure, fig.height=28, fig.width=22}
furniture_spiral %>% 
  ggplot(aes(x = year, y = houshold_value_dollars, fill = interaction(houshold_value_dollars, year))) +
  geom_col(show.legend = FALSE, width = 0.35) +
  labs(
    title = "ASSESSED  VALUE  OF  HOUSEHOLD  AND  KITCHEN  FURNITURE\nOWNED  BY  GEORGIA  NEGROES.",
    y = NULL
  ) +
  scale_fill_manual(
    values = c("#d6aaa2", "#b5b0bd", "#bca48d", "#ddb04d", "#d8c8b7", "#c94355", "white") 
    ) +
  scale_x_discrete(
    limits = rev(levels(furniture_spiral$year))
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 35, face = "bold"),
    axis.text.x = element_blank(),
    plot.background = element_rect(margin(r = 10, unit = "in"),fill = "antiquewhite2"),
    panel.background = element_rect("antiquewhite2"),
  ) +
  coord_polar(theta = "y")


ggsave("challenge7.png", units = "in", width = 22, height = 28)
```
